### ISSUE TITLE
Add CI job to deploy DAG

### ISSUE THREAD

**Issue by pankajastro** [astronomer/ask-astro#52]
currently, looks like we do not have automation to sync the astro prod/dev instance dag with main branch. I feel we should add a CI job for the same

**Comment by davidgxue** [comment]
Closing this issue. This may not be as useful and could have harmful effects. Since we do not do release version branching, between previous release and next all changes are merged to main, in such cases when merge conflicts or accidental unintended interactions occur between 2 PRs merged next to each other, the code get broken. Deploys to the Production servers should strictly occur after thorough testing before a new version release to avoid the issue I described above. Thus, continuously integration to prod does not make sense but introduces additional risks. It may make sense for Dev server's DAGs but at this time it's tradeoff of complexity vs productivity it boosts isn't worth it.
