### ISSUE TITLE
Integrate Ask-astro prod and Ask-Astro dev with Langsmith

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#66]
- [x] Integrate Ask-astro prod slackbot with Langsmith
- [x] Integrate Ask-Astro dev slackbot with Langsmith
- [x] Document the change.
- [x] Create a separate project for dev 
- [x] Debug why sending through slack cannot generate correct result on Langsmith

**Comment by Lee-W** [comment]
I think for this one, we already finished the integration and project creation but we might need to check why the slack part doesn't work as expected. Currently, asking on slack will only send the first (or previous?) question to langsmith instead of the current one. We guess this might be related to cache

**Comment by Lee-W** [comment]
@sunank200 I've tested with ask-astro-local (the workspace I created this morning) and ask-astro-dev and it seems I'm not able to replicate this issue again. My guess is it might be a langsmith issue. I'll close this issue for now. But please reopen it if you feel I miss anything.
